import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Trisha Lim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Trisha Lim
        </h1>

        <br />

        <p>
          Hey, I'm Trisha! 👋
        </p>

        <p>
          I'm a Full Stack Engineer specializing in React + Next.js + TypeScript with
          5 years experience building single page applications.
          I'm dedicated to delivering great user experiences, writing clean code,
          and working closely with designers.
        </p>

        <p>
          I've worked on large B2B apps and content-managed websites for various clients in the US,
          New Zealand and Australia. I've mostly done this remotely, working with teams across
          different timezones.
        </p>

        <hr />
      </main>

    </div>
  )
}

export default Home
